export const UPGRADES = {
  request_tracing: {
    id:       'request_tracing',
    name:     'Request Tracing',
    icon:     '🔎',
    category: 'observability',
    desc:     'See the live incoming request queue and watch requests flow into threads.',
    cost:     20,
    requires: null,
    effects:  { flash: 'Request Tracing unlocked!', showQueue: true },
  },
  monitoring: {
    id:       'monitoring',
    name:     'Monitoring',
    icon:     '📊',
    category: 'observability',
    desc:     'GVL wait %, memory usage and thread activity timeline.',
    cost:     40,
    requires: 'request_tracing',
    effects:  { flash: 'Monitoring unlocked!', monitorUnlock: true },
  },
  throughput_graph: {
    id:       'throughput_graph',
    name:     'Throughput Graph',
    icon:     '📈',
    category: 'observability',
    desc:     'Live req/min chart showing how throughput evolves as you scale.',
    cost:     60,
    requires: 'request_tracing',
    effects:  { flash: 'Throughput Graph unlocked!', monitorUnlock: true },
  },
  mixed_requests: {
    id:       'mixed_requests',
    name:     'Mixed Workload',
    icon:     '🟡',
    category: 'traffic',
    desc:     'Unlock POST /checkout — 50% I/O. Higher reward, more GVL contention.',
    cost:     80,
    requires: null,
    effects:  { flash: 'Mixed Workload unlocked!' },
  },
  report_requests: {
    id:       'report_requests',
    name:     'PDF Reports',
    icon:     '🔴',
    category: 'traffic',
    desc:     'Unlock GET /export.pdf — 90% CPU. High reward, pure GVL killer.',
    cost:     120,
    requires: 'mixed_requests',
    effects:  { flash: 'PDF Reports unlocked!' },
  },
  process_monitor: {
    id:       'process_monitor',
    name:     'Process Monitor',
    icon:     '🔬',
    category: 'observability',
    desc:     'Per-process CPU / I/O / GVL wait breakdown. Reveals live state badges on process headers.',
    cost:     80,
    requires: 'monitoring',
    effects:  { flash: 'Process Monitor unlocked!', monitorUnlock: true, enableProcessMonitor: true },
  },
};
