export const UPGRADES = {
  request_tracing: {
    id:       'request_tracing',
    name:     'Request Tracing',
    icon:     '🔎',
    category: 'observability',
    desc:     'See the live incoming request queue and watch requests flow into threads.',
    cost:     20,
    requires: null,
    effects:  { flash: 'Request Tracing unlocked!', showQueue: true },
  },
  monitoring: {
    id:       'monitoring',
    name:     'Monitoring',
    icon:     '📊',
    category: 'observability',
    desc:     'GVL wait %, memory usage and thread activity timeline.',
    cost:     40,
    requires: 'request_tracing',
    effects:  { flash: 'Monitoring unlocked!', monitorUnlock: true },
  },
  throughput_graph: {
    id:       'throughput_graph',
    name:     'Throughput Graph',
    icon:     '📈',
    category: 'observability',
    desc:     'Live req/min chart showing how throughput evolves as you scale.',
    cost:     60,
    requires: 'request_tracing',
    effects:  { flash: 'Throughput Graph unlocked!', monitorUnlock: true },
  },
  mixed_requests: {
    id:       'mixed_requests',
    name:     'Mixed Workload',
    icon:     '🟡',
    category: 'traffic',
    desc:     'Unlock POST /checkout — 50% I/O. Higher reward, more GVL contention.',
    cost:     80,
    requires: null,
    effects:  { flash: 'Mixed Workload unlocked!' },
  },
  report_requests: {
    id:       'report_requests',
    name:     'PDF Reports',
    icon:     '🔴',
    category: 'traffic',
    desc:     'Unlock GET /export.pdf — 90% CPU. High reward, pure GVL killer.',
    cost:     120,
    requires: 'mixed_requests',
    effects:  { flash: 'PDF Reports unlocked!' },
  },
  marketing_1: {
    id:              'marketing_1',
    name:            'Campaign I',
    icon:            '📣',
    category:        'marketing',
    desc:            'Small ad spend. 3 req/s incoming traffic.',
    cost:            50,
    requires:        null,
    spawnPerInterval: 3,
    effects:         { flash: 'Campaign I launched! Traffic up.' },
  },
  marketing_2: {
    id:              'marketing_2',
    name:            'Campaign II',
    icon:            '📣',
    category:        'marketing',
    desc:            'Social media push. 5 req/s.',
    cost:            150,
    requires:        'marketing_1',
    spawnPerInterval: 5,
    effects:         { flash: 'Campaign II launched! Traffic spike.' },
  },
  marketing_3: {
    id:              'marketing_3',
    name:            'Campaign III',
    icon:            '📣',
    category:        'marketing',
    desc:            'Influencer deal. 8 req/s.',
    cost:            300,
    requires:        'marketing_2',
    spawnPerInterval: 8,
    effects:         { flash: 'Campaign III launched! Major spike.' },
  },
  marketing_4: {
    id:              'marketing_4',
    name:            'Campaign IV',
    icon:            '📣',
    category:        'marketing',
    desc:            'TV spot. 12 req/s. Server under pressure.',
    cost:            500,
    requires:        'marketing_3',
    spawnPerInterval: 12,
    effects:         { flash: 'Campaign IV launched! Server sweating.' },
  },
  marketing_5: {
    id:              'marketing_5',
    name:            'Campaign V',
    icon:            '🚀',
    category:        'marketing',
    desc:            'Viral launch. 18 req/s. Servers melting.',
    cost:            800,
    requires:        'marketing_4',
    spawnPerInterval: 18,
    effects:         { flash: 'Campaign V launched! Servers melting.' },
  },
  process_monitor: {
    id:       'process_monitor',
    name:     'Process Monitor',
    icon:     '🔬',
    category: 'observability',
    desc:     'Per-process CPU / I/O / GVL wait breakdown. Reveals live state badges on process headers.',
    cost:     80,
    requires: 'monitoring',
    effects:  { flash: 'Process Monitor unlocked!', monitorUnlock: true, enableProcessMonitor: true },
  },
};
