export const UPGRADES = {
  nano_vps: {
    id:       'nano_vps',
    name:     'Nano VPS',
    icon:     '🖥️',
    category: 'infra',
    desc:     '512 MB RAM · 1 vCPU. Your first cloud server — just enough to run a basic Rails app.',
    cost:     0,
    isFree:   true,
    cores:    1,
    requires: null,
    effects:  { flash: 'Nano VPS online! Deploy your first process.' },
  },
  small_vps: {
    id:       'small_vps',
    name:     'Small VPS',
    icon:     '🖥️',
    category: 'infra',
    desc:     '1 GB RAM · 2 vCPU. Unlocks a second process. Up to 8 threads total.',
    cost:     300,
    cores:    2,
    requires: 'nano_vps',
    effects:  { flash: 'Upgraded to Small VPS — 2 vCPU, 1 GB RAM!', setMem: 1024 },
  },
  medium_vps: {
    id:       'medium_vps',
    name:     'Medium VPS',
    icon:     '🖥️',
    category: 'infra',
    desc:     '2 GB RAM · 4 vCPU. Up to 4 processes, 16 threads total.',
    cost:     600,
    cores:    4,
    requires: 'small_vps',
    effects:  { flash: 'Upgraded to Medium VPS — 4 vCPU, 2 GB RAM!', setMem: 2048 },
  },
  large_vps: {
    id:       'large_vps',
    name:     'Large VPS',
    icon:     '🖥️',
    category: 'infra',
    desc:     '4 GB RAM · 8 vCPU. Up to 8 processes, 32 threads total.',
    cost:     1200,
    cores:    8,
    requires: 'medium_vps',
    effects:  { flash: 'Upgraded to Large VPS — 8 vCPU, 4 GB RAM!', setMem: 4096 },
  },
  request_tracing: {
    id:             'request_tracing',
    name:           'Request Tracing',
    icon:           '🔎',
    category:       'observability',
    desc:           'See the live incoming request queue and watch requests flow into threads.',
    cost:           20,
    requires:       null,
    requiresThread: true,
    effects:        { flash: 'Request Tracing unlocked!', showQueue: true },
  },
  memory_meter: {
    id:             'memory_meter',
    name:           'Memory Meter',
    icon:           '💾',
    category:       'observability',
    desc:           'Live RAM bar showing used vs available memory. Threads, processes and active requests all consume RAM.',
    cost:           15,
    requires:       null,
    requiresThread: true,
    effects:        { flash: 'Memory Meter unlocked!', monitorUnlock: true },
  },
  monitoring: {
    id:       'monitoring',
    name:     'Monitoring',
    icon:     '📊',
    category: 'observability',
    desc:     'GVL wait % and thread activity timeline. See exactly which threads are blocked on the GVL.',
    cost:     40,
    requires: 'request_tracing',
    effects:  { flash: 'Monitoring unlocked!', monitorUnlock: true },
  },
  memory_profiler: {
    id:       'memory_profiler',
    name:     'Memory Profiler',
    icon:     '🔬',
    category: 'observability',
    desc:     'Breakdown of RAM by category: Rails base, threads, processes, active requests and fibers.',
    cost:     80,
    requires: 'memory_meter',
    effects:  { flash: 'Memory Profiler unlocked!', monitorUnlock: true },
  },
  throughput_graph: {
    id:       'throughput_graph',
    name:     'Throughput Graph',
    icon:     '📈',
    category: 'observability',
    desc:     'Live req/min chart showing how throughput evolves as you scale.',
    cost:     60,
    requires: 'request_tracing',
    effects:  { flash: 'Throughput Graph unlocked!', monitorUnlock: true },
  },
  mixed_requests: {
    id:             'mixed_requests',
    name:           'Mixed Workload',
    icon:           '🟡',
    category:       'traffic',
    desc:           'Unlock POST /checkout — 50% I/O. Higher reward, more GVL contention.',
    cost:           100,
    requires:       null,
    requiresThread: true,
    effects:        { flash: 'Mixed Workload unlocked!' },
  },
  report_requests: {
    id:       'report_requests',
    name:     'PDF Reports',
    icon:     '🔴',
    category: 'traffic',
    desc:     'Unlock GET /export.pdf — 90% CPU. High reward, pure GVL killer.',
    cost:     180,
    requires: 'mixed_requests',
    effects:  { flash: 'PDF Reports unlocked!' },
  },
  marketing_1: {
    id:              'marketing_1',
    name:            'Campaign I',
    icon:            '📣',
    category:        'marketing',
    desc:            'Small ad spend. 1 req/s incoming traffic.',
    cost:            60,
    requires:        null,
    requiresThread:  true,
    spawnPerInterval: 1,
    effects:         { flash: 'Campaign I launched! Traffic up.' },
  },
  marketing_2: {
    id:              'marketing_2',
    name:            'Campaign II',
    icon:            '📣',
    category:        'marketing',
    desc:            'Social media push. 3 req/s.',
    cost:            180,
    requires:        'marketing_1',
    spawnPerInterval: 3,
    effects:         { flash: 'Campaign II launched! Traffic spike.' },
  },
  marketing_3: {
    id:              'marketing_3',
    name:            'Campaign III',
    icon:            '📣',
    category:        'marketing',
    desc:            'Influencer deal. 5 req/s.',
    cost:            400,
    requires:        'marketing_2',
    spawnPerInterval: 5,
    effects:         { flash: 'Campaign III launched! Major spike.' },
  },
  marketing_4: {
    id:              'marketing_4',
    name:            'Campaign IV',
    icon:            '📣',
    category:        'marketing',
    desc:            'TV spot. 8 req/s. Server under pressure.',
    cost:            800,
    requires:        'marketing_3',
    spawnPerInterval: 8,
    effects:         { flash: 'Campaign IV launched! Server sweating.' },
  },
  marketing_5: {
    id:              'marketing_5',
    name:            'Campaign V',
    icon:            '🚀',
    category:        'marketing',
    desc:            'Viral launch. 12 req/s. Servers melting.',
    cost:            1600,
    requires:        'marketing_4',
    spawnPerInterval: 12,
    effects:         { flash: 'Campaign V launched! Servers melting.' },
  },
  fiber_scheduler: {
    id:             'fiber_scheduler',
    name:           'Fiber Scheduler',
    icon:           '🪡',
    category:       'runtime',
    desc:           'Each thread multiplexes many fibers. I/O phases run concurrently — CPU phases are serialized (cooperative scheduling, not GVL contention).',
    cost:           5000,
    requires:       null,
    requiresThread: true,
    effects:        { flash: 'Fiber Scheduler enabled! Threads now multiplex I/O.' },
  },
  ractors: {
    id:             'ractors',
    name:           'Ractors',
    icon:           '⚗️',
    category:       'runtime',
    desc:           'Each thread becomes its own GVL domain. True CPU parallelism — no more GVL_WAIT between workers. (Dream version — see the real story at purchase time.)',
    cost:           10000,
    requires:       null,
    requiresThread: true,
    effects:        { flash: 'Ractors enabled! Every thread is now its own GVL domain.', enableRactors: true },
  },
  process_monitor: {
    id:       'process_monitor',
    name:     'Process Monitor',
    icon:     '🔬',
    category: 'observability',
    desc:     'Per-process CPU / I/O / GVL wait breakdown. Reveals live state badges on process headers.',
    cost:     80,
    requires: 'monitoring',
    effects:  { flash: 'Process Monitor unlocked!', monitorUnlock: true, enableProcessMonitor: true },
  },
};
